#!/bin/sh

#  generateTechMap.inc.sh
#  yosys-xc
#
#  Created by Jim Lawson on 7/16/18.
#  Copyright © 2018 Jim Lawson. All rights reserved.
# Generate the file containing the stdcells_code.
# We assume we're running under Xcode.
INPUT_FILE=$1
OUTPUT_FILE=$2
mkdir -p "$(dirname -- "$OUTPUT_FILE")"
echo "// autogenerated from $INPUT_FILE" > $OUTPUT_FILE.new
echo "static char stdcells_code[] = {" >> $OUTPUT_FILE.new
od -v -td1 -An $INPUT_FILE | sed -e 's/[0-9][0-9]*/&,/g' >> $OUTPUT_FILE.new
echo "0};" >> $OUTPUT_FILE.new
mv $OUTPUT_FILE.new $OUTPUT_FILE
